### PR TITLE
Fix: ED25519 SSH keys not working

### LINKED ISSUE #1289: SFTP: Invalid passphrase for key file when using ED25519 keys
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

Use a ED25519 ssh key to connect without passphrase, built-in SFTP client displays the error mentioning "Invalid passphrase for key file".

Even with a ED25519 key with passphrase, entering the correct passphrase results in the same error message displayed.

(Just using an RSA key currently)

### Environment

Acode version: 1.11.1 (957) (f-droid)
Android version: 14
Webview: 135.0.7049.100 (com.google.android.webview)

### If applicable, add mockups / screenshots regarding your vision

_No response_

### If applicable, attach your Acode.log file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by UnschooledGamer**
# About the Issue

Fixes #1289 , And original https://github.com/Acode-Foundation/Acode/issues/674

The issue can be more clearly visible in the logcat of Android/ADB:

```java.io.IOException: Ed25519 KeyFactory not available``` 

Leading to Errors ```
Invalid passphrase for key file
com.sshtools.common.publickey.InvalidPassphraseException: Ed25519 KeyFactory not available```

# Solution/Workaround

This Pull updates BC to atleast `1.79` (that's a little higher than maverick ssh client's one) while maintaining combability to not BREAK the ssh or sftp client Library.

Attempting to fix those issues mentioned above.

I'll try creating an Issue/inform on maverick after this Pull Request.

### CODE REVIEW

**Comment by UnschooledGamer** [comment]
SPECIAL THANKS for ideas(or maybe thoughts 🙃): 
- https://stackoverflow.com/questions/55123228/java-security-nosuchalgorithmexception-no-such-algorithm-ecdsa-for-provider-bc#comment130201211_55123856 
- https://github.com/serso/web3a/blob/4dda74db948f8cbd9a79ba4b9ab456316ea52c4d/app/src/main/java/org/solovyev/android/web3a/App.java#L47

it's not copied 🙃, I had ideas for it originally, for checking the implementation of bc in maverick SSH client in my debuggings, and updating it somehow as cordova is weird/different from `pom.xml`!

File: src/plugins/sftp/src/com/foxdebug/sftp/Sftp.java [hunk 1]
```diff
@@ -178,7 +181,18 @@ public void run() {
               ContentResolver contentResolver = context.getContentResolver();
               InputStream in = contentResolver.openInputStream(uri);
 
-              JCEProvider.enableBouncyCastle(true);
+              com.sshtools.common.logger.Log.getDefaultContext().enableFile(com.sshtools.common.logger.Log.Level.DEBUG, new File("/storage/emulated/0/Android/data/com.foxdebug.acode/synergy.log"));
```
Comment (RohitKushvaha01) [inline src/plugins/sftp/src/com/foxdebug/sftp/Sftp.java]: Do not use absolute path, this will break the free version. Use the ``Environment`` class to get the path instead.

Comment (UnschooledGamer) [reply src/plugins/sftp/src/com/foxdebug/sftp/Sftp.java]: Please help out by Using `Ctrl+g` (Add a suggestion).

Thank You.

Comment (UnschooledGamer) [reply src/plugins/sftp/src/com/foxdebug/sftp/Sftp.java]: Fixed, Kindly review again. Now using [`context` to retrieve those](https://developer.android.com/reference/android/content/Context#getExternalFilesDir(java.lang.String))

**Review by RohitKushvaha01 — APPROVED** [review]

**Comment by UnschooledGamer** [comment]
Let's wait longer in case someone says. It's not working for them. Otherwise, we can merge this in a Few Days

**Comment by UnschooledGamer** [comment]
Merging for now, I'll do follow-up PR (if it doesn't work for someone) 😅
